os: osx
osx_image: xcode9.4
install:
- curl -o Unity.pkg https://download.unity3d.com/download_unity/f2cce2a5991f/MacEditorInstaller/Unity-2017.4.10f1.pkg
- sudo installer -dumplog -package Unity.pkg -target /
script:
- ./build.bash
